### PR TITLE
Fix private registries credentials handling and public registries

### PR DESCRIPTION
**Pull request by gionn**
Stomp my feet on #1142, forked https://github.com/sous-chefs/docker/pull/1143 hoping to get it merged soon.

Thanks!

### CODE REVIEW

**Comment by ramereth** [comment]
This will need to wait until we finish up some Chef 17 updates on some dependent cookbooks that are currently breaking the testing. We'll let you know when we're ready for you to rebase.

**Comment by gionn** [comment]
@ramereth are you still interest on this pr? thanks

**Comment by ramereth** [comment]
@gionn yes! Apologies for not replying sooner. Will you be able to rebase and resolve the conflicts?

**Comment by gionn** [comment]
@ramereth done

**Comment by kitchen-porter** [comment]
Released as: [8.2.3](https://github.com/sous-chefs/docker/releases/tag/8.2.3)

**Pull request merged**
