### PR TITLE
Add volume_prune resource

### LINKED ISSUE #1240: docker_volume_prune resource
### :speaking_head: Foreword

Similar to the `docker_image_prune` resource, that would be great to have a `docker_volume_prune` to remove all local volumes not used by at least one container. This resource could be notified to free up storage on the host.

### Reference

- [`docker volume prune` command](https://docs.docker.com/engine/reference/commandline/volume_prune/)

### PR DESCRIPTION
**Pull request by bmhughes**
# Description

- Add volume_prune resource

## Issues Resolved

- Closes #1240 

## Check List

- [x] A summary of changes made is included in the CHANGELOG under `## Unreleased`
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by damacus** [comment]
@bmhughes how're you getting on with this one?

**Comment by bmhughes** [comment]
I'd completely forgotten about this to be honest @damacus! I'll see if I can get it sorted this week.

**Comment by damacus** [comment]
No rush. 
If you need a hand feel free to ping

**Comment by damacus** [comment]
@bmhughes ping

**Review by damacus — APPROVED** [review]

**Comment by kitchen-porter** [comment]
Released as: [11.8.0](https://github.com/sous-chefs/docker/releases/tag/11.8.0)

**Pull request merged**
