### PR TITLE
docker_installation_package: support for ubuntu 24.04

### PR DESCRIPTION
**Pull request by san983**
# Description

- Adds support for Ubuntu 24.04 (nobel) for module docker_installation_package
- Also adds 22.04 to CI

This is similar to the PR https://github.com/sous-chefs/docker/pull/1225

## Issues Resolved

n/a

## Check List

- [ ] A summary of changes made is included in the CHANGELOG under `## Unreleased`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Review by Stromweld — APPROVED** [review]

**Comment by san983** [comment]
Thanks @Stromweld, let me know if there is anything else needed to push this forward :)

**Comment by bmhughes** [comment]
> Thanks @Stromweld, let me know if there is anything else needed to push this forward :)

Hi @san983,

Thanks for this, could you add a changelog entry and I'll look at getting this merged.

Thanks!

**Comment by san983** [comment]
> > Thanks @Stromweld, let me know if there is anything else needed to push this forward :)
> 
> Hi @san983,
> 
> Thanks for this, could you rebase on main and add a changelog entry and I'll look at getting this merged.
> 
> Thanks!

Done!

**Comment by kitchen-porter** [comment]
Released as: [11.4.0](https://github.com/sous-chefs/docker/releases/tag/11.4.0)

**Pull request merged**
