### PR TITLE
Add debian 11 support

### PR DESCRIPTION
**Pull request by zabudskyi**
Signed-off-by: PavloZabudskyi <pavlo.zabudskyi@gmail.com>

# Description

Add debian 11 support

## Issues Resolved
(https://github.com/sous-chefs/docker/issues/1207)

## Check List

- [ ] A summary of changes made is included in the CHANGELOG under `## Unreleased`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by ramereth** [comment]
@zabudskyi looks as though upstream doesn't have it ready in the repos yet?

**Comment by PavloZabudskyi** [comment]
@ramereth it installs docker in `integration (debian-11, install-and-stop)` test
```
          * execute[apt-get -q update] action run
            - execute ["apt-get", "-q", "update"]
          - force update new lists of packages
             
             * apt_package[docker-ce] action install
        - install version 5:20.10.11~3-0~debian-bullseye of package docker-ce
           
           * docker_service[default] action restart
             * docker_service_manager_systemd[default] action restart
        * service[docker] action disable
```
In `integration (debian-11, installation-script-test)` there is weird source list generated
```
             + sh -c echo "deb [arch=amd64] https://download.docker.com/linux/debian 11 test" > /etc/apt/sources.list.d/docker.list
```
I

**Comment by ramereth** [comment]
@zabudskyi I created #1209 to resolve the issues in the `installation-package` suite. I also filed https://github.com/docker/docker-install/issues/265 which addresses the issue in the `installation-script-test` suite.

Let's wait until both of those get resolved/merged. If the upstream issue doesn't get addressed in a few days, let's just remove it from the CI matrix until it does get fixed.

**Comment by zabudskyi** [comment]
@ramereth no updates in https://github.com/docker/docker-install/issues/265
Lets remove test for now?

**Comment by zabudskyi** [comment]
@ramereth please have a look. I removed debian-11 from ci matrix.

**Comment by ramereth** [comment]
@zabudskyi I just wanted you to remove it from the one suite that was failing. Can you please do that?

**Review by Xorima — APPROVED** [review]

**Review by ramereth — APPROVED** [review]

**Comment by kitchen-porter** [comment]
Released as: [10.1.6](https://github.com/sous-chefs/docker/releases/tag/10.1.6)

**Pull request merged**
